
[workspace]
resolver = "2"
members = ["emulator", "asm-ir", "assembler", "armes-elf", "linker", "readelf", "newdisk"]

[patch.crates-io]
nom_locate = {git="https://github.com/ThePerkinrex/nom_locate"}